# Generated by Django 4.2.5 on 2023-10-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagecarousel',
            options={'verbose_name': 'элемент карусели', 'verbose_name_plural': 'Карусель главной страницы'},
        ),
        migrations.AlterField(
            model_name='mainpagecarousel',
            name='image',
            field=models.ImageField(upload_to='images/main_page/carousel/', verbose_name='Изображение'),
        ),
    ]
