# Generated by Django 4.2.4 on 2023-09-11 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox_type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Марка', max_length=30)),
                ('model', models.CharField(default='Модель', max_length=30)),
                ('year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('engine_volume', models.FloatField(default=1.6, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(100.0)])),
                ('odometer', models.IntegerField(default=12345, validators=[django.core.validators.MinValueValidator(1)])),
                ('drive_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.drivetype')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.fueltype')),
                ('transmission_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.transmissiontype')),
            ],
        ),
    ]
