# Generated by Django 4.2.4 on 2023-09-11 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='engine_power',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Мощность, л/с'),
        ),
        migrations.AlterField(
            model_name='drivetype',
            name='drive_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='transmissiontype',
            name='gearbox_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='brand',
            field=models.CharField(default='Марка', max_length=30, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='engine_volume',
            field=models.FloatField(default=1.6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Объем двигателя, л'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='model',
            field=models.CharField(default='Модель', max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='odometer',
            field=models.IntegerField(default=12345, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Пробег, км'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='transportcategory',
            name='category',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Категория'),
        ),
    ]
