# Generated by Django 4.2.4 on 2023-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_transport_engine_power_alter_drivetype_drive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetype',
            name='drive_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='transmissiontype',
            name='gearbox_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Тип КПП'),
        ),
    ]
