# Generated by Django 4.2.5 on 2023-09-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_drivetype_drive_type_alter_fueltype_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivetype',
            options={'verbose_name': 'Тип привода', 'verbose_name_plural': 'Типы приводы'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Тип топлива', 'verbose_name_plural': 'Типы топлива'},
        ),
        migrations.AlterModelOptions(
            name='transmissiontype',
            options={'verbose_name': 'Вид коробки передач', 'verbose_name_plural': 'Виды коробок передач'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AlterModelOptions(
            name='transportcategory',
            options={'verbose_name': 'Категория транспорта', 'verbose_name_plural': 'Категории транспорта'},
        ),
    ]
