# Generated by Django 4.2.5 on 2023-09-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0003_delete_financeexpense'),
        ('garage', '0004_alter_drivetype_options_alter_fueltype_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
