# Generated by Django 4.2.5 on 2023-09-22 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0005_delete_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Марка', max_length=30, verbose_name='Марка')),
                ('model', models.CharField(default='Модель', max_length=30, verbose_name='Модель')),
                ('year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска')),
                ('engine_volume', models.FloatField(default=1.6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Объем двигателя, л')),
                ('engine_power', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Мощность, л/с')),
                ('odometer', models.IntegerField(default=12345, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Пробег, км')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.transportcategory', verbose_name='Категория')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.drivetype', verbose_name='Привод')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.fueltype', verbose_name='Топливо')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.transmissiontype', verbose_name='Коробка')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
