# Generated by Django 4.2.5 on 2023-09-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_transport_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='fuel_type',
            field=models.ForeignKey(default='Бензин', on_delete=django.db.models.deletion.PROTECT, to='garage.fueltype', verbose_name='Топливо'),
        ),
    ]
