# Generated by Django 4.2.5 on 2023-09-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_alter_transport_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='category',
            field=models.ForeignKey(default='Автобус', on_delete=django.db.models.deletion.PROTECT, to='garage.transportcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='drive_type',
            field=models.ForeignKey(default='Задний', on_delete=django.db.models.deletion.PROTECT, to='garage.drivetype', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transmission_type',
            field=models.ForeignKey(default='Автомат', on_delete=django.db.models.deletion.PROTECT, to='garage.transmissiontype', verbose_name='Коробка'),
        ),
    ]
