# Generated by Django 4.2.5 on 2023-09-24 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_alter_transport_category_alter_transport_drive_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['brand', 'model', 'year'], 'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AddField(
            model_name='transport',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='description',
            field=models.CharField(help_text='Введите какое-нибудь описание транспортного средства.\nНапример гос. номер. Не обязательно для заполнения', max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='brand',
            field=models.CharField(help_text='Введите марку транспортного средства. Максимум 50 символов.', max_length=50, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='category',
            field=models.ForeignKey(default='Автобус', help_text='Выберите категорию транспортного средства.', on_delete=django.db.models.deletion.PROTECT, to='garage.transportcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='drive_type',
            field=models.ForeignKey(default='Задний', help_text='Выберите тип привода транспортного средства.', on_delete=django.db.models.deletion.PROTECT, to='garage.drivetype', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='engine_power',
            field=models.FloatField(help_text='Введите мощность транспортного средства.', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Мощность, л/с'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='engine_volume',
            field=models.FloatField(help_text='Введите объем двигателя транспортного средства.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Объем двигателя, л'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='fuel_type',
            field=models.ForeignKey(default='Бензин', help_text='Выберите тип топлива потребляемого транспортным средством.', on_delete=django.db.models.deletion.PROTECT, to='garage.fueltype', verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='model',
            field=models.CharField(help_text='Введите модель транспортного средства. Максимум 50 символов.', max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='odometer',
            field=models.IntegerField(help_text='Введите пробег транспортного средства.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Пробег, км'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transmission_type',
            field=models.ForeignKey(default='Автомат', help_text='Выберите вид коробки перемены передач транспортного средства.', on_delete=django.db.models.deletion.PROTECT, to='garage.transmissiontype', verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.IntegerField(default=2023, help_text='Введите год выпуска транспортного средства.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
        ),
    ]
