# Generated by Django 4.2.5 on 2023-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_alter_transport_options_transport_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.CharField(blank=True, help_text='Введите какое-нибудь описание транспортного средства.\nНапример гос. номер. Не обязательно для заполнения', max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
