# Generated by Django 4.2.5 on 2023-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_alter_transport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/garage/transport_cat/', verbose_name='Изображение'),
        ),
    ]
