# Generated by Django 4.2.5 on 2023-09-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_transportcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание транспортного средства.\nНапример гос. номер. Не обязательно для заполнения', max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
