# Generated by Django 4.2.4 on 2023-09-11 17:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0003_alter_drivetype_drive_type_alter_fueltype_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTypes',
            fields=[
                ('expense_type', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Тип расходов')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('date', models.DateField(default=datetime.date(2023, 9, 11), validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Дата')),
                ('odometer', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Пробег')),
                ('expense_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_expenses.expensetypes')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.transport', verbose_name='Транспорт')),
            ],
        ),
    ]
