# Generated by Django 4.2.4 on 2023-09-11 17:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)], verbose_name='Дата'),
        ),
    ]
