# Generated by Django 4.2.5 on 2023-09-22 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_transport'),
        ('finance_expenses', '0003_delete_financeexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)], verbose_name='Дата')),
                ('odometer', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Пробег')),
                ('expense_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_expenses.expensetypes')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.transport', verbose_name='Транспорт')),
            ],
        ),
    ]
