# Generated by Django 4.2.5 on 2023-09-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0005_financeexpense_add_date_alter_financeexpense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='expense_type',
            field=models.ForeignKey(help_text='Выберите категорию расходов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_expenses.expensetypes', verbose_name='Вид расходов'),
        ),
    ]
