# Generated by Django 4.2.5 on 2023-10-02 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0006_alter_financeexpense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='expense_type',
            field=models.ForeignKey(help_text='Выберите категорию расходов', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance_expenses.expensetypes', verbose_name='Вид расходов'),
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите пробег, на момент траты средств', verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='summ',
            field=models.FloatField(blank=True, help_text='Укажите сумму израсходованных средств.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
    ]
