# Generated by Django 4.2.5 on 2023-10-02 19:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0007_alter_financeexpense_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 2), help_text='Выберите дату', validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)], verbose_name='Дата'),
        ),
    ]
