# Generated by Django 4.2.5 on 2023-10-05 18:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0010_alter_expensetypes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='description',
            field=models.TextField(blank=True, help_text='Здесь можно написать заметки о трате', max_length=250, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 5), help_text='Выберите дату', validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 5))], verbose_name='Дата трат'),
        ),
    ]
