# Generated by Django 4.2.5 on 2023-10-05 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0011_financeexpense_description_alter_financeexpense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='summ',
            field=models.FloatField(help_text='Укажите сумму израсходованных средств.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
    ]
