# Generated by Django 4.2.5 on 2023-10-21 08:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expenses', '0012_alter_financeexpense_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 21), help_text='Выберите дату', validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 21))], verbose_name='Дата трат'),
        ),
    ]
